export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as GetStarted } from './GetStarted'
export { default as Subscribe } from './Subscribe'
export { default as Upload } from './Upload'
export { default as NotFound } from './NotFound'
